In [ ]:
import torch

In [ ]:
B, N, M, P = 2, 3, 5, 4
x = torch.randn(B, N, M)
y = torch.randn(B, M, P)
z = torch.randn(B, N, P)

z[0] = x[1] @ y[1]
# print(x[1].shape, y[1].shape , (x[1] @ y[1]).shape, z[0] == x[1] @ y[1])

x = torch.tensor([[1,2],[2,3]])
y = torch.tensor([[3,4],[4,5]])
print(x @ y)
print(x.mm(y))

x = torch.rand(3,4)
y = torch.rand(3,4)
print(torch.stack((x,y), dim = 2).shape)

In [ ]:

x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
x.shape, v.shape

4, 3
 , 3 -> 1, 3 -> 4, 3

In [ ]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

In [ ]:
# shape 3,4
'''
3,4 - 3,4 / 3,4
3,4 - 1,4 (pre-broadcast) / 3,4

1,4 mean -> 4, mean -> 4,sum
1,4 std -> 4, std -> 3,4 var (**2) , 
3,4 **2 of difference -> 3,4 of difference between mean


'''

In [ ]:
x = torch.randn(3,4)
x.sum(dim = 0, keepdim=True).shape

In [ ]:
x = torch.tensor([[1,3],[2,4]])
y = torch.tensor([[2,3],[2,3]])
((x - y)**2).sum()

In [ ]:
# given 3 , 5, calculate difference into a 3x5 matrix
x = torch.tensor([1,2,3]) # 3,
y = torch.tensor([4,5]) # 2,
y = y.view(-1, 1)
x = x.view(1,-1)
x-y


In [ ]:
x = torch.randn(3,4,5)
y = torch.randn(2,4,5)
y = y.reshape(2,20)
x = x.reshape(3,20)
x = x.unsqueeze(1)
y = y.unsqueeze(0)
x.shape, y.shape
diff1 = (x - y)
exp1 = (x - y)**2
diff1[0,0,0], exp1[0,0,0]
sum_exp = exp1.sum(2)
sqrt_sum_exp = sum_exp**(1/2)
exp1.shape, sum_exp.shape, sqrt_sum_exp.shape, sqrt_sum_exp.numel()



In [ ]:
import torch

# Create a tensor of shape (3, 4)
tensor = torch.tensor([ [8, 5, 7, 6], [12, 9, 11, 10],[4, 2, 3, 1]])

# Sort the tensor along dimension 1 (columns)
sorted_tensor, indices = torch.sort(tensor, dim=0)

# Print the sorted tensor and the indices
print("Sorted Tensor:")
print(sorted_tensor)
print("Indices:")
print(indices)
indices[:1,]


In [ ]:
tmp = torch.tensor([1, 2, 3, 2, 3, 1, 2, 3, 1, 1])
ele_count = tmp.bincount()
majority_element = torch.argmax(ele_count)
majority_count = ele_count[majority_element]
ele_count, majority_element, majority_count

In [ ]:
import torch

# Create a 3D tensor of shape (2, 2, 4)
tensor = torch.tensor([[[1, 2, 3, 2],
                         [3, 1, 1, 3]],
                        
                        [[4, 5, 5, 4],
                         [6, 7, 6, 7]]])

# Find the mode along dimension 2 (depth)
mode_values, mode_indices = torch.mode(tensor, dim=2)

# Print the mode values and their indices
print("Mode Values:")
print(mode_values)
print("Mode Indices:")
print(mode_indices)


In [ ]:
t = torch.tensor(
    [
        [1, 2, 3, 2, 3, 1, 2, 3, 1, 1],
        [1, 2, 3, 2, 3, 1, 2, 3, 1, 1]
    ]
)
t.mode(dim=1)

In [ ]:
import torch

# Create a tensor of shape (6, 4)
tensor = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16],
                       [17, 18, 19, 20],
                       [21, 22, 23, 24]])

# Split the tensor into 3 chunks along dimension 0 (rows)
chunks = torch.chunk(tensor, chunks=3)

# Print the chunks
for i, chunk in enumerate(chunks):
    print(f"Chunk {i + 1}:")
    print(chunk)
    print()


In [ ]:
def svm_loss_naive(
    W: torch.Tensor, X: torch.Tensor, y: torch.Tensor, reg: float
):
    '''
    W.shape (3073, 10))
    X.shape (10000, 3073)
    y.shape (10000,)
    '''
    dW = torch.zeros_like(W)  # initialize the gradient as zero

    # compute the loss and the gradient
    num_classes = W.shape[1] # 10
    num_train = X.shape[0] # 10000
    loss = 0.0
    for i in range(num_train): # for each image
        scores = W.t().mv(X[i]) # calculate the score for each class, result a siz 10 vector
        correct_class_score = scores[y[i]] # get the score for the correct class
        for j in range(num_classes): # for each class
            if j == y[i]: # skip the correct class
                continue
            margin = scores[j] - correct_class_score + 1  # note delta = 1
            if margin > 0:
                loss += margin # accumulate the loss
                dW[:, j] += X[i] # accumulate the gradient for incorrect classes
                dW[:, y[i]] -= X[i] # accumulate the gradient for correct class
    
    loss /= num_train
    loss += reg * torch.sum(W * W)
    # compute the gradient with respect to reg
    dW /= num_train
    dW += reg * W

In [ ]:
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([1,5,3])
a[a==b] 
a

In [ ]:
import torch

# Create a 2D tensor
t = torch.tensor([[0, 1, 0], [2, 0, 3]])

# Find the indices of non-zero elements
indices = (t > 1).nonzero()

print(indices)


In [109]:
index= torch.tensor([2, 0])
t = torch.tensor([[20, 13, 0], [2, 50, 3]])
t[torch.arange(t.shape[0]), index]+=10
t[0,0] = 5
t


tensor([[ 5, 13, 10],
        [12, 50,  3]])

In [110]:
index = (t>10).nonzero()
index[:, 1]

tensor([1, 0, 1])

In [111]:
three_ones = torch.ones(3, dtype=torch.int32).view(-1, 1)
three_ones

tensor([[1],
        [1],
        [1]], dtype=torch.int32)

In [112]:

# make a 3,2 tensor
x = torch.tensor([[1,2],[3,4],[5,6]])
x

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [113]:
x[:, index] += three_ones
x

tensor([[2, 3],
        [4, 5],
        [6, 7]])

In [125]:
index2 = torch.tensor([1,1,1])
index2

tensor([1, 1, 1])

In [132]:
x[:, index2] += three_ones
x

tensor([[ 9, 17],
        [11, 19],
        [13, 21]])

In [173]:
import torch

import torch.nn.functional as F

t = torch.tensor([[0, 0, 0], 
                  [0, 0, 0],
                  [0, 0, 0]])  # Example tensor t
x = torch.tensor([0, 1, 2, 1, 1])  # Example tensor x
y = torch.tensor([2, 2, 4])  # Example tensor y
# y = y.unsqueeze(1)
y + t

z = F.one_hot(x, num_classes=3)
z


tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1],
        [0, 1, 0],
        [0, 1, 0]])

In [169]:
import torch
import torch.nn.functional as F

# Your list
lst = [1, 0, 2, 1]

# Convert the list into a tensor
tensor = torch.tensor(lst)

# Determine the number of classes (max value in tensor plus one)
num_classes = tensor.max().item() + 1

# Perform one-hot encoding
one_hot = F.one_hot(tensor, num_classes=num_classes)

print(one_hot)


tensor([[0, 1, 0],
        [1, 0, 0],
        [0, 0, 1],
        [0, 1, 0]])


In [28]:
import torch

b = torch.randn(10,)
# Generate a random integer between 0 and 9
random_int = torch.randint(0, 10, (5,))  # Output shape: scalar
print(b[random_int])
b
# Generate a random 2x3 tensor of integers between 0 and 5
# random_tensor = torch.randint(0, 6, (2, 3))
# print(random_tensor)


tensor([ 0.4147, -1.4443,  0.2864,  0.3997,  1.8897])


tensor([ 1.0040,  0.2864, -0.8741,  0.3997,  0.4147,  0.1107, -0.2105, -0.8095,
        -1.4443,  1.8897])