In [2]:
import torch

In [3]:
B, N, M, P = 2, 3, 5, 4
x = torch.randn(B, N, M)
y = torch.randn(B, M, P)
z = torch.randn(B, N, P)

z[0] = x[1] @ y[1]
# print(x[1].shape, y[1].shape , (x[1] @ y[1]).shape, z[0] == x[1] @ y[1])

x = torch.tensor([[1,2],[2,3]])
y = torch.tensor([[3,4],[4,5]])
print(x @ y)
print(x.mm(y))

x = torch.rand(3,4)
y = torch.rand(3,4)
print(torch.stack((x,y), dim = 2).shape)

tensor([[11, 14],
        [18, 23]])
tensor([[11, 14],
        [18, 23]])
torch.Size([3, 4, 2])


In [4]:

x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
x.shape, v.shape

(torch.Size([4, 3]), torch.Size([3]))

4, 3
 , 3 -> 1, 3 -> 4, 3

In [5]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

tensor([[ 2,  2,  4],
        [ 5,  5,  7],
        [ 8,  8, 10],
        [11, 11, 13]])


In [6]:
# shape 3,4
'''
3,4 - 3,4 / 3,4
3,4 - 1,4 (pre-broadcast) / 3,4

1,4 mean -> 4, mean -> 4,sum
1,4 std -> 4, std -> 3,4 var (**2) , 
3,4 **2 of difference -> 3,4 of difference between mean


'''

'\n3,4 - 3,4 / 3,4\n3,4 - 1,4 (pre-broadcast) / 3,4\n\n1,4 mean -> 4, mean -> 4,sum\n1,4 std -> 4, std -> 3,4 var (**2) , \n3,4 **2 of difference -> 3,4 of difference between mean\n\n\n'

In [7]:
x = torch.randn(3,4)
x.sum(dim = 0, keepdim=True).shape

torch.Size([1, 4])

In [8]:
x = torch.tensor([[1,3],[2,4]])
y = torch.tensor([[2,3],[2,3]])
((x - y)**2).sum()

tensor(2)

In [9]:
# given 3 , 5, calculate difference into a 3x5 matrix
x = torch.tensor([1,2,3]) # 3,
y = torch.tensor([4,5]) # 2,
y = y.view(-1, 1)
x = x.view(1,-1)
x-y


tensor([[-3, -2, -1],
        [-4, -3, -2]])

In [10]:
x = torch.randn(3,4,5)
y = torch.randn(2,4,5)
y = y.reshape(2,20)
x = x.reshape(3,20)
x = x.unsqueeze(1)
y = y.unsqueeze(0)
x.shape, y.shape
diff1 = (x - y)
exp1 = (x - y)**2
diff1[0,0,0], exp1[0,0,0]
sum_exp = exp1.sum(2)
sqrt_sum_exp = sum_exp**(1/2)
exp1.shape, sum_exp.shape, sqrt_sum_exp.shape, sqrt_sum_exp.numel()



(torch.Size([3, 2, 20]), torch.Size([3, 2]), torch.Size([3, 2]), 6)

In [11]:
import torch

# Create a tensor of shape (3, 4)
tensor = torch.tensor([ [8, 5, 7, 6], [12, 9, 11, 10],[4, 2, 3, 1]])

# Sort the tensor along dimension 1 (columns)
sorted_tensor, indices = torch.sort(tensor, dim=0)

# Print the sorted tensor and the indices
print("Sorted Tensor:")
print(sorted_tensor)
print("Indices:")
print(indices)
indices[:1,]


Sorted Tensor:
tensor([[ 4,  2,  3,  1],
        [ 8,  5,  7,  6],
        [12,  9, 11, 10]])
Indices:
tensor([[2, 2, 2, 2],
        [0, 0, 0, 0],
        [1, 1, 1, 1]])


tensor([[2, 2, 2, 2]])

In [12]:
tmp = torch.tensor([1, 2, 3, 2, 3, 1, 2, 3, 1, 1])
ele_count = tmp.bincount()
majority_element = torch.argmax(ele_count)
majority_count = ele_count[majority_element]
ele_count, majority_element, majority_count

(tensor([0, 4, 3, 3]), tensor(1), tensor(4))

In [13]:
import torch

# Create a 3D tensor of shape (2, 2, 4)
tensor = torch.tensor([[[1, 2, 3, 2],
                         [3, 1, 1, 3]],
                        
                        [[4, 5, 5, 4],
                         [6, 7, 6, 7]]])

# Find the mode along dimension 2 (depth)
mode_values, mode_indices = torch.mode(tensor, dim=2)

# Print the mode values and their indices
print("Mode Values:")
print(mode_values)
print("Mode Indices:")
print(mode_indices)


Mode Values:
tensor([[2, 1],
        [4, 6]])
Mode Indices:
tensor([[3, 2],
        [3, 2]])


In [14]:
t = torch.tensor(
    [
        [1, 2, 3, 2, 3, 1, 2, 3, 1, 1],
        [1, 2, 3, 2, 3, 1, 2, 3, 1, 1]
    ]
)
t.mode(dim=1)

torch.return_types.mode(
values=tensor([1, 1]),
indices=tensor([9, 9]))

In [15]:
import torch

# Create a tensor of shape (6, 4)
tensor = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16],
                       [17, 18, 19, 20],
                       [21, 22, 23, 24]])

# Split the tensor into 3 chunks along dimension 0 (rows)
chunks = torch.chunk(tensor, chunks=3)

# Print the chunks
for i, chunk in enumerate(chunks):
    print(f"Chunk {i + 1}:")
    print(chunk)
    print()


Chunk 1:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Chunk 2:
tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Chunk 3:
tensor([[17, 18, 19, 20],
        [21, 22, 23, 24]])



In [20]:
def svm_loss_naive(
    W: torch.Tensor, X: torch.Tensor, y: torch.Tensor, reg: float
):
    '''
    W.shape (3073, 10))
    X.shape (10000, 3073)
    y.shape (10000,)
    '''
    dW = torch.zeros_like(W)  # initialize the gradient as zero

    # compute the loss and the gradient
    num_classes = W.shape[1] # 10
    num_train = X.shape[0] # 10000
    loss = 0.0
    for i in range(num_train): # for each image
        scores = W.t().mv(X[i]) # calculate the score for each class, result a siz 10 vector
        correct_class_score = scores[y[i]] # get the score for the correct class
        for j in range(num_classes): # for each class
            if j == y[i]: # skip the correct class
                continue
            margin = scores[j] - correct_class_score + 1  # note delta = 1
            if margin > 0:
                loss += margin # accumulate the loss
                dW[:, j] += X[i] # accumulate the gradient for incorrect classes
                dW[:, y[i]] -= X[i] # accumulate the gradient for correct class
    
    loss /= num_train
    loss += reg * torch.sum(W * W)
    # compute the gradient with respect to reg
    dW /= num_train
    dW += reg * W

tensor([ 3.8360, -2.9999,  1.4192])

In [24]:
a = torch.tensor([[1,2,3],
                  [4,5,6]])
b = torch.tensor([1,5,3])
a[a==b] 
a

tensor([1, 3, 5])

In [34]:
import torch

# Create a 2D tensor
t = torch.tensor([[0, 1, 0], [2, 0, 3]])

# Find the indices of non-zero elements
indices = (t > 1).nonzero()

print(indices)


tensor([[1, 0],
        [1, 2]])


In [59]:
d = torch.randn(12, 7)
x = torch.randn(200, 12)

a = torch.tensor([[1,2,3],[4,5,6]])
a
correct_indexes = (a % 2 == 0).nonzero()
correct_indexes

tensor([[0, 1],
        [1, 0],
        [1, 2]])

In [60]:
d,x

(tensor([[-1.1049,  0.8644,  0.7806, -0.6841,  1.0078,  0.0440,  0.7122],
         [ 0.8204,  1.1111, -0.4620, -0.6367, -1.9148,  0.2471,  1.0019],
         [ 1.3691, -0.9292, -0.3915,  0.1796,  1.3083,  1.8188,  1.7403],
         [ 0.2496,  0.7485,  0.2695, -0.2524, -1.0225,  0.0818,  0.2055],
         [-0.2462, -1.3636,  3.3463,  0.9769, -1.6396,  0.6252,  0.4008],
         [ 0.2024,  1.3180,  0.7712,  0.8677,  0.1654, -0.3589, -0.7906],
         [ 0.0428,  0.3063,  0.0335, -2.1336, -0.6052, -0.6148,  0.2939],
         [ 0.2331, -1.7201, -0.6861,  0.8103,  0.0350,  1.9017, -0.9829],
         [-1.6056,  1.3494,  0.6133, -0.7499,  0.5253, -1.9068, -1.0402],
         [ 1.1719,  0.7704, -0.5204, -0.2395,  0.4859,  0.2284,  0.7675],
         [-0.4111, -0.3527, -1.7122,  0.4032, -0.5348,  0.7909, -1.1559],
         [-0.7630,  0.8603,  0.4140,  0.8602, -0.6821,  0.0993,  1.5126]]),
 tensor([[ 0.5601,  1.3964,  0.3798,  ...,  0.0839,  0.1080,  0.2984],
         [ 0.3098,  0.2553,  0.0434,  .

In [61]:
d[:, correct_indexes[:, 1]]



tensor([[ 0.8644, -1.1049,  0.7806],
        [ 1.1111,  0.8204, -0.4620],
        [-0.9292,  1.3691, -0.3915],
        [ 0.7485,  0.2496,  0.2695],
        [-1.3636, -0.2462,  3.3463],
        [ 1.3180,  0.2024,  0.7712],
        [ 0.3063,  0.0428,  0.0335],
        [-1.7201,  0.2331, -0.6861],
        [ 1.3494, -1.6056,  0.6133],
        [ 0.7704,  1.1719, -0.5204],
        [-0.3527, -0.4111, -1.7122],
        [ 0.8603, -0.7630,  0.4140]])

In [62]:
x[correct_indexes[:, 0]]

tensor([[ 0.5601,  1.3964,  0.3798,  0.0775, -0.7145, -1.5561, -0.2181, -0.1796,
          0.4396,  0.0839,  0.1080,  0.2984],
        [ 0.3098,  0.2553,  0.0434, -0.6468,  0.6350,  0.5709,  0.0121, -1.0829,
         -1.0751, -0.1294, -1.5152,  0.5131],
        [ 0.3098,  0.2553,  0.0434, -0.6468,  0.6350,  0.5709,  0.0121, -1.0829,
         -1.0751, -0.1294, -1.5152,  0.5131]])

In [78]:
a = torch.tensor([[1,2,3,4,3,3,3],
                  [4,5,6,4,4,4,9]])
y = torch.tensor([1,2])
a[torch.arange(2),y] = -1
# a[torch.arange(2), y]
a

tensor([[ 1, -1, -1,  4,  3,  3,  3],
        [ 4, -1, -1,  4,  4,  4,  9]])