In [2]:
import torch

In [ ]:
B, N, M, P = 2, 3, 5, 4
x = torch.randn(B, N, M)
y = torch.randn(B, M, P)
z = torch.randn(B, N, P)

z[0] = x[1] @ y[1]
# print(x[1].shape, y[1].shape , (x[1] @ y[1]).shape, z[0] == x[1] @ y[1])

x = torch.tensor([[1,2],[2,3]])
y = torch.tensor([[3,4],[4,5]])
print(x @ y)
print(x.mm(y))

x = torch.rand(3,4)
y = torch.rand(3,4)
print(torch.stack((x,y), dim = 2).shape)

In [ ]:

x = torch.tensor([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = torch.tensor([1, 0, 1])
x.shape, v.shape

4, 3
 , 3 -> 1, 3 -> 4, 3

In [ ]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

In [ ]:
# shape 3,4
'''
3,4 - 3,4 / 3,4
3,4 - 1,4 (pre-broadcast) / 3,4

1,4 mean -> 4, mean -> 4,sum
1,4 std -> 4, std -> 3,4 var (**2) , 
3,4 **2 of difference -> 3,4 of difference between mean


'''

In [12]:
x = torch.randn(3,4)
x.sum(dim = 0, keepdim=True).shape

torch.Size([1, 4])

In [8]:
x = torch.tensor([[1,3],[2,4]])
y = torch.tensor([[2,3],[2,3]])
((x - y)**2).sum()

tensor(2)

In [12]:
# given 3 , 5, calculate difference into a 3x5 matrix
x = torch.tensor([1,2,3]) # 3,
y = torch.tensor([4,5]) # 2,
y = y.view(-1, 1)
x = x.view(1,-1)
x-y


tensor([[-3, -2, -1],
        [-4, -3, -2]])

In [52]:
x = torch.randn(3,4,5)
y = torch.randn(2,4,5)
y = y.reshape(2,20)
x = x.reshape(3,20)
x = x.unsqueeze(1)
y = y.unsqueeze(0)
x.shape, y.shape
diff1 = (x - y)
exp1 = (x - y)**2
diff1[0,0,0], exp1[0,0,0]
sum_exp = exp1.sum(2)
sqrt_sum_exp = sum_exp**(1/2)
exp1.shape, sum_exp.shape, sqrt_sum_exp.shape, sqrt_sum_exp.numel()



(torch.Size([3, 2, 20]), torch.Size([3, 2]), torch.Size([3, 2]), 6)

In [60]:
import torch

# Create a tensor of shape (3, 4)
tensor = torch.tensor([ [8, 5, 7, 6], [12, 9, 11, 10],[4, 2, 3, 1]])

# Sort the tensor along dimension 1 (columns)
sorted_tensor, indices = torch.sort(tensor, dim=0)

# Print the sorted tensor and the indices
print("Sorted Tensor:")
print(sorted_tensor)
print("Indices:")
print(indices)
indices[:1,]


Sorted Tensor:
tensor([[ 4,  2,  3,  1],
        [ 8,  5,  7,  6],
        [12,  9, 11, 10]])
Indices:
tensor([[2, 2, 2, 2],
        [0, 0, 0, 0],
        [1, 1, 1, 1]])


tensor([[2, 2, 2, 2]])

In [56]:
tmp = torch.tensor([1, 2, 3, 2, 3, 1, 2, 3, 1, 1])
ele_count = tmp.bincount()
majority_element = torch.argmax(ele_count)
majority_count = ele_count[majority_element]
ele_count, majority_element, majority_count

(tensor([0, 4, 3, 3]), tensor(1), tensor(4))

In [63]:
import torch

# Create a 3D tensor of shape (2, 2, 4)
tensor = torch.tensor([[[1, 2, 3, 2],
                         [3, 1, 1, 3]],
                        
                        [[4, 5, 5, 4],
                         [6, 7, 6, 7]]])

# Find the mode along dimension 2 (depth)
mode_values, mode_indices = torch.mode(tensor, dim=2)

# Print the mode values and their indices
print("Mode Values:")
print(mode_values)
print("Mode Indices:")
print(mode_indices)


Mode Values:
tensor([[2, 1],
        [4, 6]])
Mode Indices:
tensor([[3, 2],
        [3, 2]])


In [67]:
t = torch.tensor(
    [
        [1, 2, 3, 2, 3, 1, 2, 3, 1, 1],
        [1, 2, 3, 2, 3, 1, 2, 3, 1, 1]
    ]
)
t.mode(dim=1)

torch.return_types.mode(
values=tensor([1, 1]),
indices=tensor([9, 9]))

In [96]:
import torch

# Create a tensor of shape (6, 4)
tensor = torch.tensor([[1, 2, 3, 4],
                       [5, 6, 7, 8],
                       [9, 10, 11, 12],
                       [13, 14, 15, 16],
                       [17, 18, 19, 20],
                       [21, 22, 23, 24]])

# Split the tensor into 3 chunks along dimension 0 (rows)
chunks = torch.chunk(tensor, chunks=3)

# Print the chunks
for i, chunk in enumerate(chunks):
    print(f"Chunk {i + 1}:")
    print(chunk)
    print()


Chunk 1:
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

Chunk 2:
tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Chunk 3:
tensor([[17, 18, 19, 20],
        [21, 22, 23, 24]])

